openapi: 3.0.1
info:
  version: 1.0.0
  title: Stampede Server API Jobs
  description: The Stampede Server api for accessing jobs
paths:
  /api/startJob/testJob:
    summary: Start a job
    post:
      operationId: startJob
      responses:
        '200':
          description: Received the list of jobs successfully
